HUB_DOMAIN: "prod.ncc.mx"
ADM_EMAIL: "ppottier@group-martin.cloud"
Namespace: "hcce"
Container_Dockerhub_Username: "mozillareality"
Container_Tag: "stable-latest"
DB_USER: "postgres"
DB_PASS: "123456"
DB_NAME: "retdb"
DB_HOST: "pgbouncer"
DB_HOST_T: "pgbouncer-t"
PGRST_DB_URI: "postgres://$DB_USER:$DB_PASS@pgbouncer/$DB_NAME"
PSQL: "postgres://$DB_USER:$DB_PASS@pgbouncer/$DB_NAME"
SMTP_SERVER: "smtp.tem.scaleway.com"
SMTP_PORT: "587"
SMTP_USER: "ce508bf4-1116-4e6b-8070-b11ba589ea40"
SMTP_PASS: "6889c6c3-03cf-45fc-9ea9-5e033d25f79f"
NODE_COOKIE: "WL8I59mE83QaX7z1F9d"
GUARDIAN_KEY: "C27aDJz6DV4snHPLCVcJ"
PHX_KEY: "laMqCCifFDgJINg4Pekw"
SKETCHFAB_API_KEY: "5970c07c775c48d9be3041e48a56b27f"
TENOR_API_KEY: "?"
GENERATE_PERSISTENT_VOLUMES: "Yes"
PERSISTENT_VOLUME_STORAGE_CLASS: "default"   # or 'manual' for a single-node test installations
PERSISTENT_VOLUME_SIZE: "10Gi"
OVERRIDE_RETICULUM_IMAGE: "hubsfoundation/reticulum:$Container_Tag"
OVERRIDE_POSTGREST_IMAGE: "No"
OVERRIDE_POSTGRES_IMAGE: "No"
OVERRIDE_PGBOUNCER_IMAGE: "No"
OVERRIDE_HUBS_IMAGE: "dougreeder/hubs:martin-2025-12-23-04-17"
OVERRIDE_SPOKE_IMAGE: "dougreeder/spoke:martin-2025-12-23-04-05"
OVERRIDE_NEARSPARK_IMAGE: "No"
OVERRIDE_PHOTOMNEMONIC_IMAGE: "No"
OVERRIDE_DIALOG_IMAGE: "No"
OVERRIDE_COTURN_IMAGE: "No"
OVERRIDE_HAPROXY_IMAGE: "No"
